// SET USER LOGGED IN LOGGED OUT
export const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";
export const SET_USER_LOGGED_OUT = "SET_USER_LOGGED_OUT";
// LOGIN
export const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
export const HIDE_LOGIN_FORM = "HIDE_LOGIN_FORM";
export const POST_LOGIN_FORM_REQUEST = "POST_LOGIN_FORM_REQUEST";
export const POST_LOGIN_FORM_SUCCESS = "POST_LOGIN_FORM_SUCCESS";
export const POST_LOGIN_FORM_FAILED = "POST_LOGIN_FORM_FAILED";

// REISTER
export const SHOW_REGISTER_FORM = "SHOW_REGISTER_FORM";
export const HIDE_REGISTER_FORM = "HIDE_REGISTER_FORM";
export const POST_REGISTER_FORM_REQUEST = "POST_REGISTER_FORM_REQUEST";
export const POST_REGISTER_FORM_SUCCESS = "POST_REGISTER_FORM_SUCCESS";
export const POST_REGISTER_FORM_FAILED = "POST_REGISTER_FORM_FAILED";

// FORGOT PASSWORD
export const SHOW_FORGOT_PASSWORD_FORM = "SHOW_FORGOT_PASSWORD_FORM";
export const HIDE_FORGOT_PASSWORD_FORM = "HIDE_FORGOT_PASSWORD_FORM";
export const POST_FORGOT_PASSWORD_FORM_REQUEST =
  "POST_FORGOT_PASSWORD_FORM_REQUEST";
export const POST_FORGOT_PASSWORD_FORM_SUCCESS =
  "POST_FORGOT_PASSWORD_FORM_SUCCESS";
export const POST_FORGOT_PASSWORD_FORM_FAILED =
  "POST_FORGOT_PASSWORD_FORM_FAILED";
export const POST_PASSWORD_REQUEST = "POST_PASSWORD_REQUEST";
export const POST_PASSWORD_SUCCESS = "POST_PASSWORD_SUCCESS";
export const POST_PASSWORD_FAILED = "POST_PASSWORD_FAILED";

// SOCIAL LOGIN
export const POST_SOCIAL_LOGIN_FORM_REQUEST = "POST_SOCIAL_LOGIN_FORM_REQUEST";
export const POST_SOCIAL_LOGIN_FORM_SUCCESS = "POST_SOCIAL_LOGIN_FORM_SUCCESS";
export const POST_SOCIAL_LOGIN_FORM_FAILED = "POST_SOCIAL_LOGIN_FORM_FAILED";

//change password
export const POST_CHANGE_PASSWORD_REQUEST = "POST_CHANGE_PASSWORD_REQUEST";
export const POST_CHANGE_PASSWORD_SUCCESS = "POST_CHANGE_PASSWORD_SUCCESS";
export const POST_CHANGE_PASSWORD_FAILURE = "POST_CHANGE_PASSWORD_FAILURE";

// SOCIAL REGISTER
export const POST_SOCIAL_REGISTER_FORM_REQUEST =
  "POST_SOCIAL_REGISTER_FORM_REQUEST";
export const POST_SOCIAL_REGISTER_FORM_SUCCESS =
  "POST_SOCIAL_REGISTER_FORM_SUCCESS";
export const POST_SOCIAL_REGISTER_FORM_FAILED =
  "POST_SOCIAL_REGISTER_FORM_FAILED";

// MyAccount
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const ADD_CARD = "ADD_CARD";

// MyOrders
export const POST_MYPROFILE_FORM_REQUEST = "POST_MYPROFILE_FORM_REQUEST";
export const POST_MYPROFILE_FORM_SUCCESS = "POST_MYPROFILE_FORM_SUCCESS";
export const POST_MYPROFILE_FORM_FAILED = "POST_MYPROFILE_FORM_FAILED";
export const UPDATE_MYPROFILE_FORM_SUCCESS = "UPDATE_MYPROFILE_FORM_SUCCESS";

// MyOrders
export const FETCH_MYORDERSLIST_REQUEST = "FETCH_MYORDERSLIST_REQUEST";
export const FETCH_MYORDERSLIST_SUCCESS = "FETCH_MYORDERSLIST_SUCCESS";
export const FETCH_MYORDERSLIST_FAILED = "FETCH_MYORDERSLIST_FAILED";

export const FETCH_MYORDERDETAILS_REQUEST = "FETCH_MYORDERDETAILS_REQUEST";
export const FETCH_MYORDERDETAILS_SUCCESS = "FETCH_MYORDERDETAILS_SUCCESS";
export const FETCH_MYORDERDETAILS_FAILED = "FETCH_MYORDERDETAILS_FAILED";

// MANAGE ADDRESSES
export const FETCH_ADDRESS_REQUEST = "FETCH_ADDRESS_REQUEST";
export const FETCH_ADDRESS_SUCCESS = "FETCH_ADDRESS_SUCCESS";
export const FETCH_ADDRESS_FAILED = "FETCH_ADDRESS_FAILED";

export const POST_ADD_ADDRESS_REQUEST = "POST_ADD_ADDRESS_REQUEST";
export const POST_ADD_ADDRESS_SUCCESS = "POST_ADD_ADDRESS_SUCCESS";
export const POST_ADD_ADDRESS_FAILED = "POST_ADD_ADDRESS_FAILED";

export const PUT_UPDATE_ADDRESS_REQUEST = "PUT_UPDATE_ADDRESS_REQUEST";
export const PUT_UPDATE_ADDRESS_SUCCESS = "PUT_UPDATE_ADDRESS_SUCCESS";
export const PUT_UPDATE_ADDRESS_FAILED = "PUT_UPDATE_ADDRESS_FAILED";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_REQUEST_SUCCESS = "DELETE_ADDRESS_REQUEST_SUCCESS";
export const DELETE_ADDRESS_REQUEST_FAILED = "DELETE_ADDRESS_REQUEST_FAILED";

export const FETCH_LOCATION_FROM_IP_REQUEST = "FETCH_LOCATION_FROM_IP_REQUEST";
export const FETCH_LOCATION_FROM_IP_SUCCESS = "FETCH_LOCATION_FROM_IP_SUCCESS";
export const FETCH_LOCATION_FROM_IP_FAILURE = "FETCH_LOCATION_FROM_IP_FAILURE";

export const REMOVE_ADDRESS_REQUEST = "REMOVE_ADDRESS_REQUEST";
export const REMOVE_ADDRESS_SUCCESS = "REMOVE_ADDRESS_SUCCESS";
export const REMOVE_ADDRESS_FAILURE = "REMOVE_ADDRESS_FAILURE";

export const SET_DELIVERY_OPTION = "SET_DELIVERY_OPTION";
export const SET_SELECTED_ADDRESS = "SET_SELECTED_ADDRESS";
export const SET_DELIVERY_DISTANCE = "SET_DELIVERY_DISTANCE";
export const SET_IS_TAKE_AWAY = "SET_IS_TAKE_AWAY";

// Delivery Time
export const SET_DELIVERY_TIME = "SET_DELIVERY_TIME";

// PICKUP TIME
export const SET_PICKUP_TIME = "SET_PICKUP_TIME";

export const SET_PHONE_CODE = "SET_PHONE_CODE";

export const SET_DELIVERY_COST = "SET_DELIVERY_COST";

export const SET_DEFAULT_ADDRESSS = "SET_DEFAULT_ADDRESSS";
